# pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: counter-service-pv
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  awsElasticBlockStore:
    volumeID: vol-05364789863bf51b8 
    fsType: ext4