version: 0.2

env:
  variables:
    COMPONENT: "counter-service"
    AWS_ACCOUNT_ID: "630943284793"

phases:
  pre_build:
    commands:
      - env
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPO_ECR="${AWS_ACCOUNT_ID}.dkr.${AWS_DEFAULT_REGION}.amazonaws.com"
      - aws ecr get-login-password | docker login --username AWS --password-stdin $REPO_ECR
      - REPOSITORY_URI=${REPO_ECR}/$COMPONENT
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
