version: 0.2
env:
  variables:
    REPO_ECR: "630943284793.dkr.ecr.eu-central-1.amazonaws.com/counter-service"
    AWS_DEFAULT_REGION: "eu-central-1"
    AWS_ACCOUNT_ID: "630943284793"
phases:
  pre_build:
    commands:

      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password \
        --region $(AWS_DEFAULT_REGION) | docker login \
        --username AWS \
        --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=${REPO_ECR}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
