apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.appName }}
  namespace: {{ .Values.global.namespace }}
data:
  REDIS_HOST: {{ .Values.configmap.data.REDIS_HOST }}
  REDIS_PORT: "{{ .Values.configmap.data.REDIS_PORT }}"