---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: prod
  namespace: prod
spec:
  interval: 1m0s
  ref:
    branch: flask-eks-app
  secretRef:
    name: flux-system
  url: ssh://git@github.com/RivkaKremer/counter-service
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: prod
  namespace: prod
spec:
  interval: 10m0s
  path: ./k8s-cluster-app/flux-flag
  prune: true
  sourceRef:
    kind: GitRepository
    name: prod
  validation: client
